import type { Realm } from '../types';

export const realm5: Realm = {
  id: 'r5',
  title: 'Generative Models & LLMs',
  subtitle: 'The age of synthesis',
  icon: '✨',
  description: 'VAEs, GANs, diffusion models, and large language models — the architectures that generate images, text, audio, and video.',
  prerequisiteRealmIds: ['r3'],
  quests: [
    {
      id: 'r5q1',
      title: 'Generative Foundations',
      description: 'The core principles behind learning to generate data from a distribution.',
      chapters: [
        {
          id: 'r5q1c1',
          title: 'Generative vs. Discriminative Models',
          lesson: {
            text: 'Discriminative models learn P(y|x) — the conditional distribution of labels given input. Generative models learn P(x) or P(x,y) — the full data distribution. Generative models can synthesize new data, impute missing values, and detect anomalies. They\'re harder to train but more powerful: knowing P(x,y) implies knowing P(y|x) by Bayes.',
            formula: 'Discriminative: model P(y|x) directly\nGenerative: model P(x) or P(x,y) — Bayes gives P(y|x)',
          },
          challenge: {
            type: 'quiz',
            prompt: 'Which task REQUIRES a generative model (cannot be done with a discriminative model alone)?',
            options: [
              'Generating novel photorealistic images',
              'Classifying images as cats or dogs',
              'Predicting house prices from features',
              'Detecting fraud in transactions',
            ],
            correctAnswer: 'Generating novel photorealistic images',
            explanation: 'Generation requires learning P(x) — the distribution over images. Discriminative models only learn decision boundaries between classes; they cannot sample from the data distribution.',
          },
        },
        {
          id: 'r5q1c2',
          title: 'Latent Variable Models',
          lesson: {
            text: 'Latent variable models assume each observation x is generated by an unobserved latent variable z: P(x) = ∫ P(x|z)P(z) dz. z captures the underlying "code" (e.g., identity, pose). Learning requires integrating over z — usually intractable, motivating EM, variational inference, and VAEs.',
            formula: 'P(x) = ∫ P(x|z)P(z) dz\nPosterior: P(z|x) = P(x|z)P(z)/P(x)  (intractable in general)',
          },
          challenge: {
            type: 'quiz',
            prompt: 'Why is exact computation of P(z|x) in latent variable models usually intractable?',
            options: [
              'Computing P(x) = ∫P(x|z)P(z)dz requires integrating over all possible z — exponential in latent dimension',
              'P(z|x) is always uniform and uninformative',
              'Gradient descent cannot optimize latent variables',
              'The posterior is always Gaussian by the CLT',
            ],
            correctAnswer: 'Computing P(x) = ∫P(x|z)P(z)dz requires integrating over all possible z — exponential in latent dimension',
            explanation: 'The normalization constant P(x) requires marginalizing z — integrating over the entire latent space. For high-dimensional continuous z, this integral has no closed form (unless the model is conjugate).',
          },
        },
        {
          id: 'r5q1c3',
          title: 'Autoencoders',
          lesson: {
            text: 'An autoencoder compresses input x to a latent code z = Enc(x), then reconstructs x̂ = Dec(z), trained to minimize reconstruction loss ‖x − x̂‖². The bottleneck forces learning of a compressed representation. Denoising autoencoders corrupt the input and learn to reconstruct the clean version — more robust representations.',
            formula: 'Encoder: z = f_θ(x)\nDecoder: x̂ = g_φ(z)\nLoss: L = ‖x − x̂‖²',
          },
          challenge: {
            type: 'quiz',
            prompt: 'A plain autoencoder is NOT well-suited for generation because:',
            options: [
              'The latent space is unstructured — sampling random z may give nonsensical outputs',
              'Autoencoders are too large to train',
              'The reconstruction loss prevents learning useful features',
              'Autoencoders require labeled data',
            ],
            correctAnswer: 'The latent space is unstructured — sampling random z may give nonsensical outputs',
            explanation: 'Autoencoders are trained only for reconstruction — the latent space has no prior distribution enforced. Sampling a random point in latent space likely falls outside the trained region, producing garbage.',
          },
        },
        {
          id: 'r5q1c4',
          title: 'Variational Autoencoders (VAEs)',
          lesson: {
            text: 'VAEs add structure to the latent space by encoding x as a Gaussian distribution q_φ(z|x) = N(μ(x), σ²(x)I) and minimizing the ELBO: reconstruction + KL divergence from N(0,I). The reparameterization trick (z = μ + σ·ε, ε~N(0,I)) makes sampling differentiable.',
            formula: 'ELBO = E_{q}[log p(x|z)] − KL(q(z|x)‖p(z))\nReparameterization: z = μ_φ(x) + σ_φ(x) ⊙ ε, ε~N(0,I)',
          },
          challenge: {
            type: 'derivation',
            prompt: 'Understand the VAE objective by decomposing the ELBO.',
            steps: [
              {
                prompt: 'Step 1 — We want to maximize log P(x). We introduce q(z|x) and write: log P(x) = ELBO + KL(q(z|x)‖P(z|x)). Since KL ≥ 0, ELBO is a:',
                options: ['Lower bound on log P(x)', 'Upper bound on log P(x)', 'Exact estimate of log P(x)', 'The reconstruction loss'],
                correctAnswer: 'Lower bound on log P(x)',
              },
              {
                prompt: 'Step 2 — ELBO = E_q[log P(x|z)] − KL(q(z|x)‖P(z)). The first term encourages:',
                options: ['Accurate reconstruction of x from z', 'q(z|x) to match the prior N(0,I)', 'Minimizing KL divergence', 'Diversity in the latent space'],
                correctAnswer: 'Accurate reconstruction of x from z',
              },
              {
                prompt: 'Step 3 — The KL term KL(q(z|x)‖P(z)) acts as:',
                options: ['A regularizer forcing the posterior toward the prior N(0,I)', 'A reconstruction penalty', 'The gradient of the decoder', 'A capacity constraint on the encoder'],
                correctAnswer: 'A regularizer forcing the posterior toward the prior N(0,I)',
              },
            ],
          },
        },
        {
          id: 'r5q1c5',
          title: 'Flow-Based Models',
          lesson: {
            text: 'Normalizing flows learn an invertible mapping f: x → z where z~N(0,I). The change-of-variables formula gives an exact log-likelihood: log P(x) = log P(z) + log|det(∂f/∂x)|. Flows offer exact density estimation and efficient sampling. Real NVP and Glow use coupling layers with triangular Jacobians for tractable determinants.',
            formula: 'log P(x) = log P(f(x)) + log|det J_f(x)|\nJ_f = ∂f/∂x  (Jacobian)',
          },
          challenge: {
            type: 'quiz',
            prompt: 'Normalizing flows require the transformation f to be:',
            options: [
              'Invertible and have a tractable Jacobian determinant',
              'Non-differentiable at the data points',
              'A linear transformation',
              'A stochastic mapping',
            ],
            correctAnswer: 'Invertible and have a tractable Jacobian determinant',
            explanation: 'Invertibility allows both sampling (z→x) and density estimation (x→z). The Jacobian determinant accounts for volume changes — must be computable efficiently (NVP uses triangular Jacobians with O(d) determinant).',
          },
        },
        {
          id: 'r5q1boss',
          title: 'BOSS: The ELBO Engineer',
          isBoss: true,
          lesson: {
            text: 'The ELBO (Evidence Lower BOund) is the core objective of variational inference and VAEs. Understanding it deeply — not just memorizing the formula — is essential for building generative models.',
          },
          challenge: {
            type: 'design',
            prompt: 'Your VAE generates blurry images. Increasing the KL weight β (β-VAE) worsens blurriness. What is happening?',
            options: [
              'Strong KL pushes the posterior to the prior, compressing the latent space and reducing reconstruction fidelity',
              'High β means the model ignores the decoder',
              'The encoder is too large and overfits',
              'β-VAE is not suitable for image generation',
            ],
            correctAnswer: 'Strong KL pushes the posterior to the prior, compressing the latent space and reducing reconstruction fidelity',
            explanation: 'The β-VAE trades reconstruction vs. disentanglement. A high β forces the posterior to collapse toward N(0,I), limiting how much info flows through z — less info → worse reconstruction → more blur.',
          },
        },
      ],
    },
    {
      id: 'r5q2',
      title: 'Adversarial Generation',
      description: 'GANs — learning through competition between generator and discriminator.',
      prerequisiteQuestIds: ['r5q1'],
      chapters: [
        {
          id: 'r5q2c1',
          title: 'The GAN Framework',
          lesson: {
            text: 'A GAN trains two networks: Generator G maps noise z~P(z) to fake data G(z), and Discriminator D tries to distinguish real from fake. They play a minimax game: D maximizes discrimination accuracy; G minimizes it. At Nash equilibrium, G generates perfect data and D outputs 0.5 everywhere.',
            formula: 'min_G max_D V(G,D) = E_{x~P_data}[log D(x)] + E_{z~P_z}[log(1 − D(G(z)))]',
          },
          challenge: {
            type: 'quiz',
            prompt: 'At the Nash equilibrium of a GAN, the discriminator D(x) outputs:',
            options: ['0.5 for all x — it cannot distinguish real from fake', '1.0 for real, 0.0 for fake', '0.0 for all x', '1.0 for all x'],
            correctAnswer: '0.5 for all x — it cannot distinguish real from fake',
            explanation: 'At equilibrium, P_G = P_data — generated and real data are indistinguishable. The optimal D(x) = P_data(x) / (P_data(x) + P_G(x)) = 0.5 everywhere.',
          },
        },
        {
          id: 'r5q2c2',
          title: 'GAN Training Instability and Mode Collapse',
          lesson: {
            text: 'GAN training is notoriously unstable. Mode collapse occurs when G generates only a few modes of the distribution, ignoring diversity. Vanishing gradients occur when D is too good — log(1-D(G(z))) saturates. Wasserstein GAN (WGAN) uses the Earth Mover\'s distance with gradient penalty — smoother training and no mode collapse.',
            formula: 'WGAN: min_G max_{D: Lip-1} E[D(x)] − E[D(G(z))]\nGP penalty: λ·E[(‖∇D(x̂)‖ − 1)²]',
          },
          challenge: {
            type: 'concept_battle',
            prompt: 'Explain what mode collapse is and why it happens in GAN training.',
            keywords: ['generator', 'diversity', 'mode', 'discriminator', 'gradient', 'ignore', 'single', 'collapse'],
            keywordThreshold: 4,
          },
        },
        {
          id: 'r5q2c3',
          title: 'Progressive and Conditional GANs',
          lesson: {
            text: 'Progressive GAN (ProGAN) grows the network gradually — starting at 4×4 resolution and adding layers to reach 1024×1024. This stabilizes training by first learning coarse structure. Conditional GAN (cGAN) conditions both G and D on class labels or other attributes — enabling controlled generation.',
            formula: 'cGAN: G(z, y) → fake image of class y\nD(x, y) → real/fake for class y',
          },
          challenge: {
            type: 'quiz',
            prompt: 'Progressive growing of GANs stabilizes training by:',
            options: [
              'Learning coarse features first at low resolution before adding fine detail',
              'Using larger batch sizes throughout',
              'Removing the discriminator in early training',
              'Starting with a pre-trained classifier',
            ],
            correctAnswer: 'Learning coarse features first at low resolution before adding fine detail',
            explanation: 'At 4×4, the task is trivial — learn basic shapes. As resolution doubles, new layers refine the learned representation. The curriculum from coarse to fine prevents the common failure of high-res GAN training from scratch.',
          },
        },
        {
          id: 'r5q2c4',
          title: 'StyleGAN and Image Synthesis',
          lesson: {
            text: 'StyleGAN introduces a mapping network that maps z to an intermediate latent space W, then injects style at each layer via adaptive instance normalization (AdaIN). This disentangles attributes — high-level styles (face shape) at early layers, fine details (freckles) at late layers. W-space is better disentangled than Z-space.',
            formula: 'AdaIN(x, y) = y_s · (x − μ(x))/σ(x) + y_b\nStyle codes yₛ, yᵦ from W via learned affine',
          },
          challenge: {
            type: 'quiz',
            prompt: 'In StyleGAN\'s mapping network z → w, the purpose of the intermediate W space is:',
            options: [
              'To disentangle attributes by sampling from a less entangled manifold than the Gaussian prior',
              'To make sampling faster',
              'To reduce the dimensionality of the latent code',
              'To replace the discriminator with a perceptual loss',
            ],
            correctAnswer: 'To disentangle attributes by sampling from a less entangled manifold than the Gaussian prior',
            explanation: 'The Gaussian prior Z has all dimensions correlated through the learned distribution. The mapping network warps Z into W, which better matches the natural manifold of attributes — improving disentanglement and controllability.',
          },
        },
        {
          id: 'r5q2c5',
          title: 'Adversarial Examples and Robustness',
          lesson: {
            text: 'Adversarial examples are inputs with imperceptible perturbations that fool classifiers. FGSM adds ε·sign(∇_x L) to the input. PGD is the strongest first-order attack. Adversarial training (min-max training on adversarial examples) is the most effective defense but at a cost in standard accuracy.',
            formula: 'FGSM: x_adv = x + ε·sign(∇_x L(f_θ(x), y))\nAdv training: min_θ E[max_{δ:‖δ‖≤ε} L(f_θ(x+δ), y)]',
          },
          challenge: {
            type: 'design',
            prompt: 'You deploy a medical image classifier. An adversary can slightly perturb input images to cause misclassification. What defense is most principled?',
            options: [
              'Adversarial training with PGD — empirically most robust, but with accuracy/robustness tradeoff to accept',
              'Input smoothing — blur all images before inference',
              'Detect adversarial examples and reject them',
              'Use a larger model — more parameters = more robust',
            ],
            correctAnswer: 'Adversarial training with PGD — empirically most robust, but with accuracy/robustness tradeoff to accept',
            explanation: 'Detection-based defenses are often bypassed with adaptive attacks. Input smoothing destroys fine-grained medical features. Adversarial training directly optimizes for worst-case robustness — the gold standard despite lower clean accuracy.',
          },
        },
        {
          id: 'r5q2boss',
          title: 'BOSS: The GAN Strategist',
          isBoss: true,
          lesson: {
            text: 'GAN training pathologies are well-documented. This boss tests your ability to diagnose and fix training failures.',
          },
          challenge: {
            type: 'design',
            prompt: 'Your GAN generates only one type of face despite diverse training data. Generator loss is very low, discriminator loss is near zero. What\'s wrong and how do you fix it?',
            options: [
              'Mode collapse — use minibatch discrimination or WGAN-GP to force diversity',
              'Discriminator is too weak — increase its capacity',
              'Learning rate is too high — reduce both by 10×',
              'Not enough epochs — train longer',
            ],
            correctAnswer: 'Mode collapse — use minibatch discrimination or WGAN-GP to force diversity',
            explanation: 'Low G loss + near-zero D loss with low diversity = mode collapse. The generator found one face that fools the discriminator perfectly and ignores all other modes. Minibatch discrimination penalizes similar samples; WGAN-GP provides better gradient signal.',
          },
        },
      ],
    },
    {
      id: 'r5q3',
      title: 'Diffusion Models',
      description: 'The denoising framework that powers state-of-the-art image and audio generation.',
      prerequisiteQuestIds: ['r5q1'],
      chapters: [
        {
          id: 'r5q3c1',
          title: 'The Forward Diffusion Process',
          lesson: {
            text: 'Diffusion models define a forward process that gradually adds Gaussian noise to data over T steps. By step T, the data is pure noise x_T ~ N(0, I). The noise schedule β₁,...,βₜ controls the rate. A key property: x_t can be sampled directly from x₀ in one step using the cumulative noise ᾱ_t = Π(1−βₜ).',
            formula: 'q(xₜ|x₀) = N(xₜ; √ᾱₜ x₀, (1−ᾱₜ)I)\nxₜ = √ᾱₜ x₀ + √(1−ᾱₜ) ε,  ε~N(0,I)',
          },
          challenge: {
            type: 'quiz',
            prompt: 'After T=1000 diffusion steps with ᾱ_T ≈ 0, x_T is approximately:',
            options: ['Pure Gaussian noise N(0, I)', 'The original image x₀', 'The mean of the dataset', 'A uniform distribution'],
            correctAnswer: 'Pure Gaussian noise N(0, I)',
            explanation: 'When ᾱ_T → 0: x_T = √ᾱ_T x₀ + √(1−ᾱ_T)ε ≈ ε ~ N(0,I). The original signal is completely destroyed, and x_T is indistinguishable from pure noise.',
          },
        },
        {
          id: 'r5q3c2',
          title: 'Denoising Score Matching',
          lesson: {
            text: 'Score-based generative models learn the score function ∇_x log p(x) — pointing toward regions of higher data density. Denoising score matching trains a network to predict the noise ε added at each step, which is equivalent to estimating the score. At each noise level, the score tells us which direction to move to increase data likelihood.',
            formula: 'Score: ∇_x log p_σ(x) ≈ −ε_θ(x_t, t)/σ_t\nDSM loss: E[‖ε_θ(xₜ, t) − ε‖²]',
          },
          challenge: {
            type: 'quiz',
            prompt: 'In DDPM, the neural network ε_θ(xₜ, t) is trained to predict:',
            options: [
              'The noise ε that was added to create xₜ from x₀',
              'The clean image x₀ directly',
              'The next noisy image xₜ₊₁',
              'The noise schedule β_t',
            ],
            correctAnswer: 'The noise ε that was added to create xₜ from x₀',
            explanation: 'The DDPM objective is L = E[‖ε − ε_θ(√ᾱ_t x₀ + √(1−ᾱ_t)ε, t)‖²]. The network learns to predict the specific noise realization ε. Equivalently this can be reparameterized as predicting x₀.',
          },
        },
        {
          id: 'r5q3c3',
          title: 'DDPM and the Reverse Process',
          lesson: {
            text: 'DDPM (Denoising Diffusion Probabilistic Model) learns a reverse process p_θ(xₜ₋₁|xₜ) by parameterizing it as a Gaussian with mean predicted by ε_θ. Sampling: start from xₜ~N(0,I) and iteratively denoise for T steps. DDIM (Deterministic DDIM) enables faster sampling with 10-50 steps by removing the stochastic component.',
            formula: 'Reverse: p_θ(xₜ₋₁|xₜ) = N(μ_θ(xₜ,t), σ²_t I)\nμ_θ = (1/√αₜ)(xₜ − (βₜ/√(1−ᾱₜ))ε_θ(xₜ,t))',
          },
          challenge: {
            type: 'quiz',
            prompt: 'DDIM (Denoising Diffusion Implicit Models) achieves faster sampling by:',
            options: [
              'Making the reverse process deterministic — fewer steps needed since there is no accumulated stochasticity',
              'Using a smaller neural network',
              'Only denoising the low-frequency components',
              'Replacing the T-step chain with a single direct prediction',
            ],
            correctAnswer: 'Making the reverse process deterministic — fewer steps needed since there is no accumulated stochasticity',
            explanation: 'DDPM\'s stochastic sampling requires many steps to integrate out noise. DDIM defines a deterministic reverse process with the same marginals — enabling 10-50 step sampling vs. DDPM\'s 1000 steps.',
          },
        },
        {
          id: 'r5q3c4',
          title: 'Guidance — Classifier and Classifier-Free',
          lesson: {
            text: 'Classifier guidance steers generation by augmenting the score with a classifier gradient: ε̃ = ε_θ − s·√(1−ᾱ)·∇_x log p(y|x). Classifier-free guidance (CFG) trains a conditional ε_θ(x,y) and an unconditional ε_θ(x) simultaneously, then at inference: ε̃ = ε_θ(x) + s·(ε_θ(x,y) − ε_θ(x)). CFG is now the standard approach.',
            formula: 'CFG: ε̃ = ε_uncond + s·(ε_cond − ε_uncond)\nHigher guidance scale s → more faithful to condition, less diversity',
          },
          challenge: {
            type: 'design',
            prompt: 'You use Stable Diffusion with classifier-free guidance scale s=1.0. Outputs are diverse but not matching your text prompt. What should you try?',
            options: [
              'Increase guidance scale s (e.g., 7.5) — stronger conditioning signal',
              'Decrease guidance scale to 0',
              'Remove the text conditioning entirely',
              'Use fewer denoising steps',
            ],
            correctAnswer: 'Increase guidance scale s (e.g., 7.5) — stronger conditioning signal',
            explanation: 'Low guidance scale → generation ignores the condition, more like unconditional sampling. Higher s amplifies the difference between conditional and unconditional, making outputs more faithful to the prompt at the cost of diversity.',
          },
        },
        {
          id: 'r5q3c5',
          title: 'Latent Diffusion and Stable Diffusion',
          lesson: {
            text: 'Latent Diffusion Models (LDMs) apply the diffusion process in a compressed latent space (from a VQ-VAE/KL-VAE) rather than pixel space. This reduces computation ~64× for 8× spatial compression. Stable Diffusion = LDM + CLIP text encoder + cross-attention conditioning. The VAE compresses 512×512 to 64×64 latents.',
            formula: 'Encode: z = E(x), decode: x = D(z)\nDiffusion operates on z (64×64×4) not x (512×512×3)',
          },
          challenge: {
            type: 'quiz',
            prompt: 'Why does Stable Diffusion operate in latent space rather than pixel space?',
            options: [
              'Latent space is ~64× smaller — diffusion training and sampling is vastly cheaper',
              'The latent space has better perceptual quality',
              'Pixel-space diffusion cannot be conditioned on text',
              'Latent diffusion avoids mode collapse',
            ],
            correctAnswer: 'Latent space is ~64× smaller — diffusion training and sampling is vastly cheaper',
            explanation: 'Diffusion cost scales with the number of tokens. 512×512 pixels = 786K values; 64×64×4 latents = 16K values — 49× fewer. The VAE preserves perceptual quality while making diffusion tractable.',
          },
        },
        {
          id: 'r5q3boss',
          title: 'BOSS: The Diffusion Architect',
          isBoss: true,
          lesson: {
            text: 'Diffusion models now dominate image and audio generation. This boss tests your understanding of the key architectural and algorithmic choices.',
          },
          challenge: {
            type: 'design',
            prompt: 'You want to generate high-quality 1024×1024 images with text prompts at reasonable cost. Design the optimal pipeline.',
            options: [
              'Latent diffusion (LDM) + CLIP conditioning + CFG + DDIM sampling — the Stable Diffusion recipe',
              'Pixel-space DDPM + classifier guidance — most controllable',
              'GAN + CLIP loss — fastest inference',
              'VAE alone with text conditioning',
            ],
            correctAnswer: 'Latent diffusion (LDM) + CLIP conditioning + CFG + DDIM sampling — the Stable Diffusion recipe',
            explanation: 'LDM reduces compute via latent space. CLIP provides powerful text-image alignment. CFG provides text adherence without a separate classifier. DDIM enables 20-50 step sampling. This combination is the industry standard.',
          },
        },
      ],
    },
    {
      id: 'r5q4',
      title: 'Language Modeling',
      description: 'From n-gram models to neural language models and the laws of scale.',
      prerequisiteQuestIds: ['r5q1'],
      chapters: [
        {
          id: 'r5q4c1',
          title: 'N-gram Models and Perplexity',
          lesson: {
            text: 'N-gram models estimate P(wₙ|w₁,...,wₙ₋₁) ≈ P(wₙ|wₙ₋N+1,...,wₙ₋₁) using counts from a corpus. They suffer from the curse of dimensionality: exponentially many n-grams, most unseen. Perplexity = 2^{H(P,Q)} where H is cross-entropy; lower = better. A perplexity of 100 means the model is as confused as choosing uniformly from 100 options.',
            formula: 'PPL(W) = P(w₁,...,wₙ)^{−1/n} = exp(−(1/n)Σ log P(wₜ|w<t))',
          },
          challenge: {
            type: 'quiz',
            prompt: 'A language model with perplexity 50 is better than one with perplexity 200. What does this mean?',
            options: [
              'The model assigns higher probability to test data — it is less surprised by the text',
              'The model has 50 parameters vs 200',
              'The model processes 50 words per second',
              'Perplexity measures accuracy, not likelihood',
            ],
            correctAnswer: 'The model assigns higher probability to test data — it is less surprised by the text',
            explanation: 'Perplexity is the exponentiated cross-entropy: exp(H(P,Q)). Lower perplexity = lower cross-entropy = higher assigned probability to test text. A perfect model knowing the true distribution would have PPL equal to the true entropy.',
          },
        },
        {
          id: 'r5q4c2',
          title: 'Word Embeddings — Word2Vec, GloVe',
          lesson: {
            text: 'Word embeddings map words to dense vectors where semantic similarity corresponds to geometric proximity. Word2Vec Skip-gram predicts context words from a target word; CBOW predicts the target from context. GloVe factorizes the word co-occurrence matrix. These embeddings capture analogies: king − man + woman ≈ queen.',
            formula: 'Skip-gram: maximize Σ_t Σ_{j≠0} log P(wₜ₊ⱼ|wₜ)\nNegative sampling: σ(v_w · v_c) for positive, σ(−v_w · v_n) for negatives',
          },
          challenge: {
            type: 'quiz',
            prompt: 'Word2Vec embeddings are trained so that words appearing in similar contexts have:',
            options: [
              'Similar embedding vectors (high cosine similarity)',
              'Identical embeddings',
              'Orthogonal embeddings',
              'Larger L2 norms',
            ],
            correctAnswer: 'Similar embedding vectors (high cosine similarity)',
            explanation: 'The skip-gram objective pushes co-occurring words to have similar embeddings (high dot product) and non-co-occurring words to have dissimilar embeddings. Context similarity → embedding similarity.',
          },
        },
        {
          id: 'r5q4c3',
          title: 'Contextual Embeddings — ELMo, BERT',
          lesson: {
            text: 'Static embeddings give each word one vector regardless of context. ELMo computes representations from a bidirectional LSTM — "bank" gets different vectors in "river bank" vs. "bank account." BERT uses transformer encoders with masked language modeling (MLM) — predicting 15% of randomly masked tokens — and next sentence prediction.',
            formula: 'BERT MLM: maximize P(masked tokens | context)\nBERT NSP: binary prediction: is sentence B next after sentence A?',
          },
          challenge: {
            type: 'quiz',
            prompt: 'The key advantage of contextual embeddings (BERT) over static embeddings (Word2Vec) is:',
            options: [
              'The same word gets different representations depending on its context',
              'BERT uses more training data',
              'BERT is faster to train',
              'Static embeddings cannot capture word meaning at all',
            ],
            correctAnswer: 'The same word gets different representations depending on its context',
            explanation: '"Bank" in "river bank" and "bank loan" should have different representations — they have different meanings. BERT\'s attention mechanism considers all surrounding tokens, producing context-sensitive embeddings.',
          },
        },
        {
          id: 'r5q4c4',
          title: 'Autoregressive Language Models — GPT',
          lesson: {
            text: 'Autoregressive LMs model P(w₁,...,wₙ) = Π P(wₜ|w<t). GPT uses a causal (left-to-right) transformer: each position can only attend to previous positions via a causal mask. Pretraining: predict the next token on massive text corpora. This simple objective, at scale, gives remarkable few-shot capabilities.',
            formula: 'Causal LM loss: L = −Σₜ log P(wₜ | w₁,...,wₜ₋₁)\nMask: Aᵢⱼ = −∞ if j > i (future tokens)',
          },
          challenge: {
            type: 'quiz',
            prompt: 'GPT uses a causal attention mask. This means:',
            options: [
              'Position t can only attend to positions ≤ t — no peeking at future tokens',
              'All positions attend to all other positions equally',
              'Only the first token attends to all others',
              'Future tokens are masked during inference but not training',
            ],
            correctAnswer: 'Position t can only attend to positions ≤ t — no peeking at future tokens',
            explanation: 'To model P(wₜ|w<t), position t must not see wₜ₊₁,...,wₙ. The causal mask sets attention scores for future positions to −∞ (→ 0 after softmax). This enables training on all positions in parallel while respecting causality.',
          },
        },
        {
          id: 'r5q4c5',
          title: 'Scaling Laws and Emergent Behavior',
          lesson: {
            text: 'Kaplan et al. found that LLM loss follows power laws in model parameters N, data tokens D, and compute C: L ∝ N^{-α}. Chinchilla showed the optimal N/D ratio: roughly 20 tokens per parameter. Emergent abilities appear suddenly at scale — abilities (e.g., arithmetic, BIG-bench tasks) are absent below a threshold and appear discontinuously.',
            formula: 'Scaling law: L(N) = (Nc/N)^α_N\nChinchilla: optimal N and D given compute C: N ∝ C^0.5, D ∝ C^0.5',
          },
          challenge: {
            type: 'concept_battle',
            prompt: 'Explain what scaling laws are and why emergent abilities at scale are both exciting and concerning for AI safety.',
            keywords: ['scale', 'power law', 'emergent', 'threshold', 'unpredictable', 'capabilities', 'parameters', 'safety'],
            keywordThreshold: 4,
          },
        },
        {
          id: 'r5q4boss',
          title: 'BOSS: The Perplexity Oracle',
          isBoss: true,
          lesson: {
            text: 'Perplexity underpins language model evaluation. Understanding its connection to entropy and cross-entropy is essential for interpreting benchmark results.',
            formula: 'PPL = exp(−(1/n)Σ log P(wₜ|w<t))',
          },
          challenge: {
            type: 'code',
            prompt: 'Compute perplexity from a list of per-token log-probabilities (natural log). Return exp(average negative log-prob).',
            template: 'function perplexity(logProbs) {\n  const avgNegLogProb = logProbs.reduce((s, lp) => s + (-lp), 0) / logProbs.length;\n  return Math.exp(avgNegLogProb);\n}',
            validationRegex: 'Math\\.exp\\s*\\(\\s*avgNegLogProb\\s*\\)',
          },
        },
      ],
    },
    {
      id: 'r5q5',
      title: 'Large Language Models',
      description: 'Pretraining, fine-tuning, RLHF, and prompting at scale.',
      prerequisiteQuestIds: ['r5q4'],
      chapters: [
        {
          id: 'r5q5c1',
          title: 'Pretraining Objectives and Data Curation',
          lesson: {
            text: 'LLMs are pretrained on trillions of web tokens. Data quality matters more than quantity: filtering (CommonCrawl → C4), deduplication, and domain mixing affect downstream performance. Next-token prediction is the universal pretraining objective. Decoder-only models (GPT family) now dominate over masked LMs for generation tasks.',
            formula: 'Key data quality steps: dedup, filter, upsample quality\nData mix: web + books + code + math affects capabilities',
          },
          challenge: {
            type: 'quiz',
            prompt: 'Why does data deduplication matter for LLM pretraining?',
            options: [
              'Duplicate examples cause the model to memorize text rather than generalize',
              'Duplicates reduce training speed',
              'The tokenizer cannot handle repeated sequences',
              'Deduplication increases dataset diversity automatically',
            ],
            correctAnswer: 'Duplicate examples cause the model to memorize text rather than generalize',
            explanation: 'Repeated examples get higher loss weight — the model memorizes them. Deduplication ensures each text is seen roughly once, encouraging generalization. It also prevents evaluation contamination if test sets appear in training.',
          },
        },
        {
          id: 'r5q5c2',
          title: 'Fine-Tuning — Full, Instruction, and RLHF',
          lesson: {
            text: 'Supervised Fine-Tuning (SFT) on instruction-following datasets teaches the model to follow prompts. Full fine-tuning updates all parameters — expensive. Instruction tuning (InstructGPT, Alpaca) adapts a pretrained LLM to follow human instructions. RLHF further aligns outputs to human preferences using a reward model.',
            formula: 'SFT: min_θ −E[(x,y)~D_inst] log P_θ(y|x)\nRLHF: maximize E[R(x,y)] − β·KL(π‖π_SFT)',
          },
          challenge: {
            type: 'quiz',
            prompt: 'Why does SFT alone (without RLHF) often produce outputs that are unhelpful or unsafe?',
            options: [
              'SFT optimizes imitation of demonstrations, not human preference — RLHF corrects the objective',
              'SFT makes the model forget its pretraining',
              'SFT requires too much data to work well',
              'The cross-entropy loss is a poor proxy for language quality',
            ],
            correctAnswer: 'SFT optimizes imitation of demonstrations, not human preference — RLHF corrects the objective',
            explanation: 'SFT mimics demonstration authors\' styles, including their biases and failure modes. RLHF directly optimizes for what humans prefer — more helpful, harmless, and honest — through the reward model signal.',
          },
        },
        {
          id: 'r5q5c3',
          title: 'Parameter-Efficient Fine-Tuning — LoRA, Adapters',
          lesson: {
            text: 'Full fine-tuning of a 70B model requires 280GB+ of GPU memory. LoRA (Low-Rank Adaptation) freezes original weights and adds a low-rank update: W = W₀ + BA where B ∈ ℝ^{d×r}, A ∈ ℝ^{r×k}, r << min(d,k). Only A and B are trained — 0.1% of parameters. Adapters insert small bottleneck modules; prefix tuning adds learnable tokens.',
            formula: 'LoRA: ΔW = BA, rank r ≈ 8-64\nTrainable params ≈ 2·r·d per layer vs d² for full fine-tuning',
          },
          challenge: {
            type: 'quiz',
            prompt: 'LoRA works under the hypothesis that fine-tuning updates have:',
            options: [
              'Low intrinsic rank — the weight change lives in a low-dimensional subspace',
              'High rank — requiring full matrix updates',
              'Random structure that can be compressed',
              'No structure — LoRA works by coincidence',
            ],
            correctAnswer: 'Low intrinsic rank — the weight change lives in a low-dimensional subspace',
            explanation: 'Aghajanyan et al. showed that fine-tuning updates have low intrinsic dimensionality. LoRA exploits this: ΔW = BA with small r approximates the full-rank update with tiny parameter overhead.',
          },
        },
        {
          id: 'r5q5c4',
          title: 'Prompting — Zero-Shot, Few-Shot, Chain-of-Thought',
          lesson: {
            text: 'Prompting elicits capabilities from frozen LLMs. Zero-shot: task description only. Few-shot (in-context learning): k examples in the prompt. Chain-of-thought (CoT): prompt with step-by-step reasoning examples — dramatically improves multi-step reasoning. Self-consistency: sample multiple CoT paths, take majority vote.',
            formula: 'Zero-shot: [Task description] → [answer]\nFew-shot: [Example 1]...[Example k] → [answer]\nCoT: [Example + reasoning steps] → [reasoning + answer]',
          },
          challenge: {
            type: 'design',
            prompt: 'You need a model to solve 5-step math problems accurately. Which prompting strategy maximizes accuracy?',
            options: [
              'Chain-of-thought with self-consistency — step-by-step reasoning with majority vote over samples',
              'Zero-shot — just ask for the answer',
              'Few-shot with 3 answer-only examples',
              'System prompt specifying "you are a math expert"',
            ],
            correctAnswer: 'Chain-of-thought with self-consistency — step-by-step reasoning with majority vote over samples',
            explanation: 'CoT forces the model to decompose the problem, reducing arithmetic errors. Self-consistency samples multiple reasoning paths and votes — errors in individual paths tend to cancel. This dramatically outperforms direct prompting on multi-step reasoning.',
          },
        },
        {
          id: 'r5q5c5',
          title: 'LLM Evaluation and Benchmarking',
          lesson: {
            text: 'LLM evaluation is hard: benchmarks saturate (MMLU, HumanEval), and contamination (training on test sets) inflates scores. HELM evaluates multiple dimensions. Human preference evals (Chatbot Arena, LMSYS) avoid contamination. Evaluating safety, factuality, and reasoning requires specialized benchmarks.',
            formula: 'Contamination: test overlap with pretraining data → inflated scores\nChatbot Arena: ELO ranking from human preference comparisons',
          },
          challenge: {
            type: 'quiz',
            prompt: 'A model achieves 90% on MMLU. What limitation should you be aware of?',
            options: [
              'MMLU may be contaminated in pretraining data — the score may reflect memorization, not understanding',
              'MMLU only tests math, so the score is domain-limited',
              '90% is below human performance — the model is poor',
              'MMLU does not measure generation quality, only perplexity',
            ],
            correctAnswer: 'MMLU may be contaminated in pretraining data — the score may reflect memorization, not understanding',
            explanation: 'MMLU is a multiple-choice test. If MMLU questions appeared in pretraining data, the model may have memorized answers rather than learning to reason. This is why contamination testing and held-out benchmarks matter.',
          },
        },
        {
          id: 'r5q5boss',
          title: 'BOSS: The Fine-Tuning Architect',
          isBoss: true,
          lesson: {
            text: 'Fine-tuning strategy is a core production decision for LLM teams. The wrong choice wastes GPU-months or degrades model quality.',
          },
          challenge: {
            type: 'design',
            prompt: 'You have a 7B LLM and want to specialize it for medical note summarization. You have 10K examples and limited GPU (1× A100 80GB). Which approach?',
            options: [
              'LoRA fine-tuning (r=16) — fits in 80GB, updates minimal parameters, preserves base capabilities',
              'Full fine-tuning — always produces best results',
              'Zero-shot prompting only — no fine-tuning needed',
              'Train a separate small model from scratch on medical data',
            ],
            correctAnswer: 'LoRA fine-tuning (r=16) — fits in 80GB, updates minimal parameters, preserves base capabilities',
            explanation: 'Full 7B fine-tuning requires ~112GB+ for optimizer states. LoRA trains <0.1% of parameters — feasible on 1× A100. 10K examples are enough for LoRA adaptation. Full fine-tuning on 10K examples would overfit anyway.',
          },
        },
      ],
    },
    {
      id: 'r5q6',
      title: 'Multimodal Models',
      description: 'Connecting vision, language, audio, and video into unified representations.',
      prerequisiteQuestIds: ['r5q5'],
      chapters: [
        {
          id: 'r5q6c1',
          title: 'Vision-Language Alignment — CLIP',
          lesson: {
            text: 'CLIP (Contrastive Language-Image Pretraining) trains an image encoder and text encoder jointly to align matched image-text pairs and push apart non-matched ones — contrastive learning with N² pairs per batch. The resulting shared embedding space enables zero-shot classification by comparing image embeddings to class description embeddings.',
            formula: 'L = −(1/N) Σᵢ [log(exp(sᵢᵢ/τ)/Σⱼ exp(sᵢⱼ/τ)) + log(exp(sᵢᵢ/τ)/Σⱼ exp(sⱼᵢ/τ))]\nsᵢⱼ = image_i · text_j',
          },
          challenge: {
            type: 'quiz',
            prompt: 'CLIP enables zero-shot image classification by:',
            options: [
              'Comparing image embeddings to text embeddings of each class name — the closest class wins',
              'Fine-tuning on each new class with one example',
              'Using a lookup table of image-class associations',
              'Training a separate classifier head for each new task',
            ],
            correctAnswer: 'Comparing image embeddings to text embeddings of each class name — the closest class wins',
            explanation: 'CLIP\'s joint embedding space means "a photo of a dog" and a dog image are close together. At test time, embed the image, embed all class descriptions as text, find the nearest text embedding — that\'s the predicted class.',
          },
        },
        {
          id: 'r5q6c2',
          title: 'Image Generation from Text',
          lesson: {
            text: 'Text-to-image systems combine a text encoder (CLIP/T5) with a generative model. DALL-E 2 uses CLIP embeddings + diffusion. Stable Diffusion uses cross-attention to condition each diffusion step on text. Imagen uses a cascade of diffusion models (64→256→1024) conditioned on T5 embeddings.',
            formula: 'Cross-attention: Q=decoder features, K=V=text embeddings\nAt each denoising step, text guides spatial generation',
          },
          challenge: {
            type: 'quiz',
            prompt: 'In Stable Diffusion, text conditioning is injected via cross-attention. The text features act as:',
            options: [
              'Keys and Values that the image features (queries) attend to at each denoising step',
              'The initial noise xₜ',
              'A scalar multiplier on the noise prediction',
              'The final classifier that selects the output image',
            ],
            correctAnswer: 'Keys and Values that the image features (queries) attend to at each denoising step',
            explanation: 'Each U-Net block in Stable Diffusion has a cross-attention layer: Q comes from noisy latent features, K and V from the CLIP/text encoder output. Each spatial position can attend to relevant text tokens.',
          },
        },
        {
          id: 'r5q6c3',
          title: 'Audio and Speech Generation',
          lesson: {
            text: 'AudioLM uses a hierarchical tokenization: semantic tokens (HuBERT, captures content) + acoustic tokens (SoundStream, captures audio quality). Generation is autoregressive over token sequences. Voicebox uses a non-autoregressive diffusion approach. MusicGen conditions on text descriptions to generate music.',
            formula: 'Waveform → Semantic tokens (HuBERT) → Acoustic tokens (SoundStream)\nAutoregressive: P(tokens) = Π P(tokₜ | tok<t)',
          },
          challenge: {
            type: 'quiz',
            prompt: 'Why do modern speech synthesis models use a two-level tokenization (semantic + acoustic tokens)?',
            options: [
              'Semantic tokens capture content/meaning independently of voice quality; acoustic tokens add fine-grained audio details',
              'Single tokenization is too slow',
              'Acoustic tokens are used for training, semantic tokens for inference',
              'The two levels correspond to phonemes and words',
            ],
            correctAnswer: 'Semantic tokens capture content/meaning independently of voice quality; acoustic tokens add fine-grained audio details',
            explanation: 'Separating semantics (what is said) from acoustics (how it sounds) gives controllability: you can change the voice while keeping content, or generate content-consistent continuations. This hierarchical approach improves quality and controllability.',
          },
        },
        {
          id: 'r5q6c4',
          title: 'Video Generation',
          lesson: {
            text: 'Video generation extends image diffusion to spatiotemporal volumes. Sora (OpenAI) uses a "spacetime patch" transformer (DiT) trained on variable-length, variable-resolution videos. The key challenge: temporal consistency (objects don\'t teleport between frames) and computational cost (~10K tokens per second of video).',
            formula: 'Video patches: (t, h, w) → 3D tokens\nTemporal attention: attend across frames at same spatial location',
          },
          challenge: {
            type: 'quiz',
            prompt: 'The key challenge unique to video generation (vs. image generation) is:',
            options: [
              'Temporal consistency — maintaining coherent motion and object identity across frames',
              'Higher resolution — videos require more pixels',
              'Text conditioning — video descriptions are longer',
              'Training data — there is less video data than image data',
            ],
            correctAnswer: 'Temporal consistency — maintaining coherent motion and object identity across frames',
            explanation: 'Generating each frame independently would produce flickering and inconsistent objects. The model must learn motion dynamics, physics, and 3D consistency across time — qualitatively harder than single-image generation.',
          },
        },
        {
          id: 'r5q6c5',
          title: 'Unified Multimodal Architectures',
          lesson: {
            text: 'Unified models (GPT-4V, Gemini, LLaVA) process multiple modalities in one transformer. Vision tokens from a visual encoder (ViT/CLIP) are projected into the LLM\'s embedding space and concatenated with text tokens. The LLM reasons over the joint token sequence. This "any-to-any" approach enables visual question answering, captioning, and image understanding.',
            formula: 'Input: [vision tokens | text tokens]\nProjection: visual_embed = MLP(ViT(image))\nLLM processes: concat([visual_embed, text_embed])',
          },
          challenge: {
            type: 'concept_battle',
            prompt: 'Explain how LLaVA-style visual language models work and what makes them effective at visual reasoning.',
            keywords: ['visual encoder', 'projection', 'embedding', 'text tokens', 'attention', 'reasoning', 'align', 'LLM'],
            keywordThreshold: 4,
          },
        },
        {
          id: 'r5q6boss',
          title: 'BOSS: The Multimodal Architect',
          isBoss: true,
          lesson: {
            text: 'Multimodal systems are the frontier of AI engineering. This boss tests your system-design intuition for building production multimodal AI.',
          },
          challenge: {
            type: 'design',
            prompt: 'You are building a medical AI assistant that must analyze X-ray images and answer doctor questions about them. Design the core architecture.',
            options: [
              'ViT vision encoder → MLP projection → pretrained medical LLM with visual tokens via cross-attention or concatenation',
              'CNN classifier that outputs a diagnosis class + text template to fill in',
              'OCR the image to extract text, then use text-only LLM',
              'Train separate image and text models and average their outputs',
            ],
            correctAnswer: 'ViT vision encoder → MLP projection → pretrained medical LLM with visual tokens via cross-attention or concatenation',
            explanation: 'The LLaVA/GPT-4V architecture: encode image → project into LLM space → LLM reasons over image + question tokens. This leverages the LLM\'s language understanding and the ViT\'s visual encoding. The MLP projector aligns the embedding spaces.',
          },
        },
      ],
    },
  ],
};
